### ISSUE TITLE
吊大鱼或者魔王很容易拉满失败

### ISSUE THREAD

**Issue by SilverSpear1031** [Using1174/cq-scripts#1]
建议改一下配置，不过红色区域拉鱼速度是最快的
扯到鱼后第一次按满的时间
'Dim FirstPressFishTime = 2000
' 绿色未满长按时长
Dim PULL_LONG_PRESS_MSECS = 100
' 挣扎节点每次按住多久
Dim PULL_PRESS_MSECS = 0
' 拉到红色之后等待多少毫秒
Dim PULL_FULL_DELAY = 90

**Comment by Using1174** [comment]
我是用电脑模拟器跑的，在非常流畅的情况下这些参数钓鱼的速度是最快的，实测只有大概千分之几的概率会让鱼跑掉。如果运行的设备比较卡的话，这种配置是会增加力度拉满，鱼跑掉的概率。
这种情况下可以自行减少红色区域附近的按压时间。比如：
```
' 绿色未满长按时长
Dim PULL_LONG_PRESS_MSECS = 120
' 挣扎节点(红线)每次按住多久
Dim PULL_PRESS_MSECS = 10
' 拉过红色等待多少毫秒
Dim PULL_FULL_DELAY = 30
```
