### ISSUE TITLE
装睡的人是叫不醒的

### ISSUE THREAD

**Issue by EluvK** [Using1174/cq-scripts#2]
我自己也写了一个，通过判断进度条的位置来控制松放力度，只要设备正常不卡，试过7000条鱼不漏。

**Comment by Using1174** [comment]
是的。把力度控制放低一些，就可以保证鱼不会跑掉，但是会牺牲一些效率。

**Comment by lllhhhh** [comment]
可以把调节分辨率吗

**Comment by EluvK** [comment]
>           可以把调节分辨率吗

我的是720*1280。适配模拟器和红手指，主要是买了红手指挂机方便点

**Comment by lllhhhh** [comment]
可以分享一下吗
谢谢

**Comment by ms860309** [comment]
你好我嘗試修改fishbar, 因爲一直讀取不到
放寬到0.7依然不能
https://imgur.com/a/nO1LwSk

**Comment by ms860309** [comment]
我解決了
問題在pull抓色

**Comment by SG-XM** [comment]
> 我解決了 問題在pull抓色

请问方便共享一下吗
